# Generated by Django 4.1.4 on 2022-12-23 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_cuerpo_comentario_comentarios_comentario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticia',
            old_name='user',
            new_name='autor',
        ),
        migrations.RemoveField(
            model_name='comentarios',
            name='aprobado',
        ),
        migrations.AlterField(
            model_name='comentarios',
            name='noticia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Comentarios', to='app.noticia'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='categorias',
            field=models.ManyToManyField(related_name='Noticia', to='app.categoria'),
        ),
    ]
